### ISSUE TITLE
Activity management

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#12]
We need one or more person coordinate all the different activities:
- climbing
- soccer
- basketball
- indoor skateboard/BMX
- outdoor BMX
- frisbee
- maybe board games (?)

@eurucamp is working on a nice app to organize activities during conferences that might be helpful for us.  The app is not public yet, but you can ask @argorak or @myabc if you want to have access to the repo. (completely new app this year, we can use it and help with development.)

**Comment by raucao** [comment]
I think we shouldn't organize too many, so that there's room for people to organize their own activities. Worked out great at EuruCamp. In my opinion the ones that take a lot of room in the main hall might be the best to omit for now, i.e. soccer and basketball. We could rather do climbing in all slots and then have the rest of the hall for participant-organized activities. Does that make sense?

**Comment by raucao** [comment]
Oh, and as with the other stuff: 1 person/issue for one activity. ;)

Btw, the new activities app will be ready for testing next week I heard.

**Comment by moonglum** [comment]
See #11 – IMHO, those tickets should be combined. I suggest to close this ticket.
