### ISSUE TITLE
Quiz game

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#38]
How about doing a quiz game on stage on Saturday night after dinner? I'd be willing to moderate.

As we have the creators of Nerdpursuit among us, we could use that and create a simple game out of it. Or we could use something like https://jeopardylabs.com and do a Jeopardy-style game.

It'd be quite simple to set up. The main thing to organize upfront is probably building (or finding) the buzzer devices. Maybe we can hack something real quick with Anykey? /cc @a2800276

Interested?

**Comment by a2800276** [comment]
We could even have a little hardware session for railscamp participants to build the hardware themselves...

I was actually planning to do an angular frontend / go backend workshop with @schorsch we could expand this to include a small hardware hack, I'll ask @mattikra if he has time. "Build a nerdpursuit jeopardy..."

**Comment by raucao** [comment]
> We could even have a little hardware session for railscamp participants to build the hardware themselves...

Sounds great! And with some preparation it should be easy enough to build in an hour or two, right?

**Comment by a2800276** [comment]
I thought it would be nice to build the whole thing (Frontend, Backend, Hardware all without Rails!) as one Session of the camp. Should be doable in a day with minimal preparation... 

Matthias is up for it as well. He would do the Hardware part, Schorsch would lead the angular frontend and me the go backend ...

We'd get a small budget for parts, right? :) Our current guestimate is ~€150, mainly because (big) buttons are fairly expensive.
