### ISSUE TITLE
Drinks

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#5]
We need somebody to organize drinks, alcoholic as well as non-alcoholic.

At Raislove we always get our drinks from http://getraenkeservice-net.de/

**Comment by jhilden** [comment]
The venue also wanted to sent me the contact to their regular drink supplier.  Then we can just compare prices.

Also we can use the bar that they have for serving the drinks and they have 4 big fridges + a "Kühlkammer", so all the drinks will be nice and cool and we don't have to rent any extra equipment.

**Comment by raucao** [comment]
Yay!

We should also have a list where people can volunteer to keep the bar for an hour or so. Like with the reception.

**Comment by Uepsilon** [comment]
Did someone took care about it? Otherwise i'd try to get some numbers from different services. Are there some special things to know or is it just beer (kölsch and pils), soda (mixed) and club mate? 
At iacologne where different juices etc. which was quite cool.

**Comment by jhilden** [comment]
This issue is still up for grabs and any help would be appreciated.

FYI:  PutPat is going to sponsor 10 cases of beer.

I would suggest we get the following types of drinks:
- Kölsch  (suggestion:  Mühlenkölsch)
- Pils  (any suggestions?)
- Coke  (suggestion:  Afri Cola)
- Water, carbonated & uncarbonated  (whatever is cheapest)
- Club Mate

We just have to figure out the right amounts.  I think it would make sense to make a Google Spreadsheet to calculate the right amounts.  We should plan to order a good amount more, since we'll only have to pay what we actually drink.

I don't think we will have cups at the venue, so we should try to get small bottles (e.g. for the water).

> At iacologne where different juices etc. which was quite cool.

Let's figure out how much more that would cost compared to the basic selection above.

In addition to Railslove's Getränkeservice that I linked above this is the information I got from the venue:

> fass und flasche ist unser lieferant, aber aktiv getränke soll wohl besser sein.

Let's quickly compare prices and then decide on a supplier.

**Comment by Uepsilon** [comment]
I've created a [Spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0AkRu3FtKME1ydENLU2s2T3JEakhqd3hjaU5GRWlseVE&usp=sharing). Maybe someone with a little more experience in this may predict which amount of stuff we'll need. 

Since 4 fridges are available, I guess we don't need any further, do we? What about a beer pump or would you like to go with bottled beer only? 

Anyway, i'll ask at [several](http://www.fassundflasche.de/) [different](http://www.aktivgetraenke.de/) [service](http://getraenkeservice-net.de/shop/) [provider](http://www.pm-getraenke.de/) for prices and will keep you updated.

**Comment by raucao** [comment]
The Sünner brewery is like 100m beeline from the venue. Maybe we should just get large kegs from them, and if we're lucky they'll lend us a pump as well...

**Comment by Uepsilon** [comment]
I guess we'll get the Pump from all shops when we order kegs and we don't have to settle with Sünner (not to be picky or so) but can choose which one we'd like. And even if not, I don't think a pump is that expensive.

Big downside with a Keg: You have to have someone around who at least know how to open a keg properly without spilling all the beer. And it would be even better if you have some barkeeper who keeps tapping so it goes 
quite fast. 

I'm preferring bottles as you do not need glasses too. But I'll ask for both prices so we can compare.

**Comment by Uepsilon** [comment]
fixed access to spreadsheet..

**Comment by Uepsilon** [comment]
@jhilden the numbers you provided are per day, right? i've added another bunch of numbers what i think (after talking with ben) per person for the event (incl. warmup). do you agree on them?

**Comment by Uepsilon** [comment]
Response 1:
P&M Getränke (Bonn) are not interested. 

Response 2: https://docs.google.com/file/d/1Xc9LP_Sqr6PQQo04Qw66U8F3TpfCOs8UKo4vs7k5oCVIUhV1MdVKvHu3j6h0/edit?usp=sharing

Please notice that these prices are before tax, so it'll be around 2400€ if we return all bottles unbroken ;) 

I guess we can save some money by switching from Fritz Cola / Orange / etc. to the Coke-Pendant. But I'll ask for smaller water-bottles, because with the big ones we need to have glasses / cups around. And i'm not sure about the amount of club-mate. Isn't it too much? :D

And I can ask for different sorts of Kölsch and Pils too. I've asked for some other sorts, they gave me only this one. Which one would you prefer?

**Comment by raucao** [comment]
I don't understand that calculation. Are these 35 crates etc each?

**Comment by Uepsilon** [comment]
Amount = Number of Crates with each 24x 0,33l (or water 12x 0,7l) each.

**Comment by raucao** [comment]
Ok, that's _way_ too much from our past experience. I'll try to have another look at it tomorrow and esp. find the numbers from last RailsCamp. Unfortunately I don't have time today.

**Comment by Uepsilon** [comment]
I talked to several ppl. including Ben Kasselmann, he told be to calculat about 5 Softdrinks per Person / Day and 1,5l Beer per Person / Party. That's what I did (check the Spreadsheet). Calculating with 150 ppl those are the results

**Comment by Uepsilon** [comment]
Response Aktivgetränke (Summed up in a Spreadsheet I created, but i used the numbers).

The Sums below the articles are for bottles only, because I think KEGs will be hard to handle (and not cheaper at all) 

https://docs.google.com/spreadsheet/ccc?key=0AkRu3FtKME1ydE1Mcm9EQnJjZ1ZlTGRPNFp2Wi1lbVE&usp=sharing

edit: achja, pro VOLLEM kasten, den wir zurück geben berechnen sie uns 0,75€ zzgl. MwSt.

**Comment by jhilden** [comment]
so what is the conclusion on the 2 suppliers and their prices?

**Comment by Uepsilon** [comment]
i think aktivegetränke is a bit cheaper, but i'm still waiting for the reply of the other one (i've asked for other sorts of limonad / beer and mentioned that we're a non-profit event).. i'm going to call them tomorrow if they haven't send anything.. 

I don't think the prices will change much so i'm thinking drinks will cost around 2400€ (not including pawn / pfand which we'll hopefully return). What was planned for drinks? Do we have to cut some edges here?

**Comment by raucao** [comment]
1500,-. And I still think it's too much. Still haven't had time to look up our last numbers, though. Will do it tomorrow finally!

**Comment by raucao** [comment]
Ok, last time, with about 80 attendees, we had 400 EUR in the budget, and we had plenty of drinks left over. I'm not sure if that was actually the number in the end, because I cannot find the invoice (and I probably never received one, because I didn't handle it last time).

I think we should calculate with about 150 people. Usually a single person will have 2 large beers per night on average, and about 1.5l of non-alcoholic drinks per day. A buffer of 30% on those numbers should be sufficient. You could even double these and have less than the current calculation I believe.

**Comment by raucao** [comment]
Oh, and we can add a little more beer this time for the open Saturday night party I guess.

**Comment by Uepsilon** [comment]
Ich hab nun mit Getränke Arndt gesprochen. Die Frau die das Angebot erstellt hat ist erst Montag wieder im Haus. Der Herr mit dem ich telefoniert habe hat mir aber schon mal zugesagt, dass die Kommissionsgebühren komplett weg fallen (unter der Voraussetzung, dass wir nicht einfach blind bestellen und dann 50% zurück gehen lassen). 

Wenn wir jetzt noch die Preise von normaler Cola etc. bekommen und kleine Wasserflaschen nehmen (damit wir keine Gläser benötigen), sind die wieder mein Favorit. Vorallem haben die nichts von einer Anzahlung gesagt. 

Ich werde noch mal die Mengen überarbeiten (ich halbier mal die Mate, das sind 800 Flaschen / >5 Flaschen pro Nase wenn alle 150 trinken. Damit sparen wir alleine 400€).

**Comment by Uepsilon** [comment]
@skddc we have 10 crates from putpat in addition to the ones we order. i guess we are well-supplied with beer. ;) in fact, we might even order a little less kölsch. I've forgot about those crates. 

i've added price-tables to the [spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0AkRu3FtKME1ydENLU2s2T3JEakhqd3hjaU5GRWlseVE#gid=0), but remember that water-prices from getränke-arndt are incorrect since they are for 0,7l bottles.

**Comment by raucao** [comment]
There's an average of 14 beer per person in the sheet. Just saying.

**Comment by Uepsilon** [comment]
doh, i played with the numbers and forgot about it.. i've reverted it to 10 per person (0,33l) for 2 days, which would sum up to 1,5l per day.. that was the sum i was told to go with.. plus the 10 crates from putpat. i guess we won't run out of beer before we run out of internet. ;) before we order we can change the estimated number of people to something more realistic. i guess 130?

**Comment by wingfire** [comment]
Has someone checked out http://fassundflasche.de/ they are close to the community and made a good service for [Sigint](http://sigint.ccc.de) and [FrOSCon](http://www.froscon.de).

**Comment by Uepsilon** [comment]
I did now, as i'm still waiting for a new offer from Getränke Arndt. I'd like to place an Order today / tomorrow, so if somebody wants to play with the number: DO IT NOW!

**Comment by Uepsilon** [comment]
New prices from Getränke Arndt (kölsch is a bit cheaper, soda-prices are as expected, except for water which would cost 10.30€ per crate for small bottles, compared to 2.85€ for normal 0,7l bottles)..

Fass und Flasche hasn't responded to my email yet, although I even called them. But they promised to send me an offer today. 

@skddc: Do you still feel that it is too much to drink per person? Please make some suggestions in the Spreadsheet.

**Comment by raucao** [comment]
Looks fine to me. I don't see numbers for water in there. We need plenty of it, because it's going to be the hottest weekend ever. Forecast currently says 37℃ on Sunday.

**Comment by Uepsilon** [comment]
Since Fass und Flasche has not responded to my request, I think we should go with Getränke Arndt. 

@skddc There are two prices:
10,30€ per Crate (24x0,33l -> 7,92l total) 
2,85€ per Crat (12x0,7l -> 8,4l total)

I think there is no need to think which to choose. 

@jhilden @thilo Can you please tell me if the Price is okay? ~1600€ without deposit. Everything that is left over can be returned without extra costs. If the price is okay, i'd order tomorrow morning so we can be sure to received the delivery on Friday. 

I think we'll have to pay in advance, which would be around 2500€ incl. deposit. But I'm not sure about it and will ask when placing the order. Who can do that / receive the delivery on Friday?

**Comment by raucao** [comment]
> I think we'll have to pay in advance, which would be around 2500€ incl. deposit.

That doesn't make sense if we only have to pay what we use. We might have to give a deposit in advance, but we should be billed afterwards. No?

**Comment by Uepsilon** [comment]
That's what i thought but the offer said otherwise. I'll ask tomorrow. But
even the deposit is going  to be around 1000€.
Am 23.07.2013 16:26 schrieb "Sebastian Kippe" notifications@github.com:

**Comment by Uepsilon** [comment]
Order is placed at Getränke Arndt.

They will deliver on Friday around 14:30. If anybody can be around at that time to help @jhilden to unload the truck / pack everything into the cooler, that would be great. I asked them to put the beer in the fridge before so it will hopefully be delivered already precooled.

We don't need to pay in advance, billing will be done after collecting deposit and what is left over, which will happen on Monday.

**Comment by raucao** [comment]
Ok, great. Closing the issue then. Thanks a lot for taking care of this, @Uepsilon!!
